/**
 * Regenerates TypeScript types + zod validators from the engine's Pydantic contracts.
 * Pipeline: Pydantic → JSON Schema (schemas/*.json) → src/generated/*.ts
 * CI runs this and fails if the committed output is stale.
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { jsonSchemaToZod } from "json-schema-to-zod";

const pkgDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const engineDir = join(pkgDir, "..", "..", "services", "engine");
const schemaDir = join(pkgDir, "schemas");
const outDir = join(pkgDir, "src", "generated");

const HEADER = "// GENERATED by `pnpm contracts:gen` from services/engine contracts. Do not edit.\n";

// "health_response.v1" → "HealthResponseV1"
export function exportName(contract: string): string {
  return contract
    .split(/[._]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

/**
 * Pydantic gives every property a `title`, which json-schema-to-typescript turns into
 * top-level aliases (e.g. `export type Status`). Those collide across contracts when
 * re-exported from one index, so keep only the root title.
 */
export function stripNestedTitles(schema: unknown, isRoot = true): unknown {
  if (Array.isArray(schema)) return schema.map((item) => stripNestedTitles(item, false));
  if (schema === null || typeof schema !== "object") return schema;
  const entries = Object.entries(schema as Record<string, unknown>)
    .filter(([key]) => isRoot || key !== "title")
    .map(([key, value]) => [key, stripNestedTitles(value, false)]);
  return Object.fromEntries(entries);
}

/**
 * Inline local `$ref`s ("#/$defs/X"). json-schema-to-zod does not resolve them and
 * would emit z.any() for every nested model, silently skipping validation.
 */
export function inlineRefs(schema: unknown, defs?: Record<string, unknown>): unknown {
  const root = schema as { $defs?: Record<string, unknown> };
  const table = defs ?? root?.$defs ?? {};
  const walk = (node: unknown, stack: string[]): unknown => {
    if (Array.isArray(node)) return node.map((item) => walk(item, stack));
    if (node === null || typeof node !== "object") return node;
    const obj = node as Record<string, unknown>;
    const ref = obj.$ref;
    if (typeof ref === "string" && ref.startsWith("#/$defs/")) {
      const name = ref.slice("#/$defs/".length);
      if (stack.includes(name)) throw new Error(`recursive contract model: ${name}`);
      return walk(table[name], [...stack, name]);
    }
    return Object.fromEntries(
      Object.entries(obj)
        .filter(([key]) => key !== "$defs")
        .map(([key, value]) => [key, walk(value, stack)]),
    );
  };
  return walk(schema, []);
}

/** Names a generated file exports, split into types (interface/type) and values (const). */
export function exportedNames(source: string): { types: string[]; values: string[] } {
  const types = [...source.matchAll(/^export (?:interface|type) (\w+)/gm)].map((m) => m[1] as string);
  const values = [...source.matchAll(/^export const (\w+)/gm)].map((m) => m[1] as string);
  return { types, values };
}

/**
 * Contracts can embed the same model (e.g. PalmFeaturesV1 in two requests), so
 * `export *` from every file would export duplicate names. Re-export each name once,
 * from the first file that defines it (identical definitions come from one Pydantic
 * model). Types use `export type` (required under isolatedModules).
 */
export function buildIndex(files: { module: string; source: string }[]): string {
  const seen = new Set<string>();
  const lines: string[] = [];
  const fresh = (names: string[]) => names.filter((n) => !seen.has(n) && (seen.add(n), true));
  for (const { module, source } of files) {
    const { types, values } = exportedNames(source);
    const newTypes = fresh(types);
    const newValues = fresh(values);
    if (newTypes.length) lines.push(`export type { ${newTypes.join(", ")} } from "./${module}";`);
    if (newValues.length) lines.push(`export { ${newValues.join(", ")} } from "./${module}";`);
  }
  return lines.join("\n");
}

async function main(): Promise<void> {
  rmSync(schemaDir, { recursive: true, force: true });
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });
  execFileSync("uv", ["run", "python", "-m", "grahrekha_engine.contracts.export", schemaDir], {
    cwd: engineDir,
    stdio: "inherit",
  });

  const files: { module: string; source: string }[] = [];
  for (const file of readdirSync(schemaDir).filter((f) => f.endsWith(".json")).sort()) {
    const contract = basename(file, ".json");
    const raw = JSON.parse(readFileSync(join(schemaDir, file), "utf8")) as {
      $defs?: Record<string, object>;
    };
    const schema = stripNestedTitles(raw) as { $defs?: Record<string, object> };
    const defs = schema.$defs ?? {};
    // One validator per nested model and one for the contract itself. Types are derived
    // from the validators (z.infer), so compile-time types and runtime validation can
    // never disagree.
    const models: [string, object][] = [
      ...Object.entries(defs).map(([defName, def]) => [defName, def] as [string, object]),
      [exportName(contract), schema],
    ];
    const blocks = models.map(([name, model]) => {
      const zod = jsonSchemaToZod(inlineRefs(model, defs) as object, { name: `${name}Schema` });
      return `export ${zod}\nexport type ${name} = z.infer<typeof ${name}Schema>;`;
    });
    const source = `${HEADER}import { z } from "zod";\n\n${blocks.join("\n\n")}\n`;
    writeFileSync(join(outDir, `${contract}.ts`), source);
    files.push({ module: contract, source });
  }
  writeFileSync(join(outDir, "index.ts"), `${HEADER}${buildIndex(files)}\n`);
  console.info(`generated ${files.length} contract(s)`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await main();
}
