/**
 * Regenerates TypeScript types + zod validators from the engine's Pydantic contracts.
 * Pipeline: Pydantic → JSON Schema (schemas/*.json) → src/generated/*.ts
 * CI runs this and fails if the committed output is stale.
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";
import { jsonSchemaToZod } from "json-schema-to-zod";

const pkgDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const engineDir = join(pkgDir, "..", "..", "services", "engine");
const schemaDir = join(pkgDir, "schemas");
const outDir = join(pkgDir, "src", "generated");

const HEADER = "// GENERATED by `pnpm contracts:gen` from services/engine contracts. Do not edit.\n";

// "health_response.v1" → "HealthResponseV1"
export function exportName(contract: string): string {
  return contract
    .split(/[._]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

/**
 * Pydantic gives every property a `title`, which json-schema-to-typescript turns into
 * top-level aliases (e.g. `export type Status`). Those collide across contracts when
 * re-exported from one index, so keep only the root title.
 */
export function stripNestedTitles(schema: unknown, isRoot = true): unknown {
  if (Array.isArray(schema)) return schema.map((item) => stripNestedTitles(item, false));
  if (schema === null || typeof schema !== "object") return schema;
  const entries = Object.entries(schema as Record<string, unknown>)
    .filter(([key]) => isRoot || key !== "title")
    .map(([key, value]) => [key, stripNestedTitles(value, false)]);
  return Object.fromEntries(entries);
}

async function main(): Promise<void> {
  rmSync(schemaDir, { recursive: true, force: true });
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });
  execFileSync("uv", ["run", "python", "-m", "grahrekha_engine.contracts.export", schemaDir], {
    cwd: engineDir,
    stdio: "inherit",
  });

  const names: string[] = [];
  for (const file of readdirSync(schemaDir).filter((f) => f.endsWith(".json")).sort()) {
    const contract = basename(file, ".json");
    const name = exportName(contract);
    const schema = stripNestedTitles(JSON.parse(readFileSync(join(schemaDir, file), "utf8"))) as object;
    const ts = await compile({ ...schema, title: name }, name, { bannerComment: "", additionalProperties: false });
    const zod = jsonSchemaToZod(schema, { name: `${name}Schema`, module: "esm" });
    writeFileSync(join(outDir, `${contract}.ts`), `${HEADER}${ts}\n${zod}\n`);
    names.push(contract);
  }
  const index = names.map((c) => `export * from "./${c}";`).join("\n");
  writeFileSync(join(outDir, "index.ts"), `${HEADER}${index}\n`);
  console.info(`generated ${names.length} contract(s)`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await main();
}
