import type { Database } from "./client";

/** Renders the current schema as plain SQL (tables + indexes), excluding migration bookkeeping. */
export function renderSchemaSql(db: Database): string {
  const rows = db.$client
    .prepare(
      `SELECT sql FROM sqlite_master
       WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' AND name NOT LIKE '__drizzle%'
       ORDER BY CASE type WHEN 'table' THEN 0 ELSE 1 END, name`,
    )
    .all() as { sql: string }[];
  const header =
    "-- GrahRekha schema snapshot (generated by `pnpm db:snapshot`; do not edit by hand).\n" +
    "-- One-click setup: sqlite3 var/app.db < db/schema.sql\n" +
    "PRAGMA foreign_keys = ON;\n\n";
  return header + rows.map((r) => `${r.sql};`).join("\n\n") + "\n";
}
